
export const ratingsData = [
  {    
    userEmail: "lucas.price@example.com",
    parkName: "Asser Levy Park",
    scores: {
      cleanliness: 4,
      dog_friendliness: 5,
      busyness: 3,
      water_availability: 4,
      wastebag_availability: 5,
      trash_availability: 4,
      surface: 3,
      amenities: 4,
    },
    comment: 'Really clean and lots of space for dogs.',
    dog_size: "medium"
  },

   {    
    userEmail: "ezra.kaplan@example.com",
    parkName: "Asser Levy Park",
    scores: {
      cleanliness: 5,
      dog_friendliness: 5,
      busyness: 5,
      water_availability: 4,
      wastebag_availability: 4,
      trash_availability: 3,
      surface: 4,
      amenities: 5,
    },
    comment: 'Love this place!!!!',
    dog_size: "medium"
  },
  {
       
    userEmail: "sienna.morrison@example.com",
    parkName: "Breukelen Park",
    scores: {
      cleanliness: 5,
      dog_friendliness: 4,
      busyness: 2,
      water_availability: 5,
      wastebag_availability: 3,
      trash_availability: 4,
      surface: 5,
      amenities: 3,
    },
    comment: 'Crowded in the evenings, but still nice.',
    dog_size: "small"
  },
  {
       
    userEmail: "ezra.kaplan@example.com",
    parkName: "Brooklyn Bridge Park",
    scores: {
      cleanliness: 3,
      dog_friendliness: 5,
      busyness: 4,
      water_availability: 3,
      wastebag_availability: 3,
      trash_availability: 3,
      surface: 4,
      amenities: 5,
    },
    comment: 'Not clean enough but dog friendly.',
    dog_size: "large"
  },
  {
       
    userEmail: "maya.singh@example.com",
    parkName: "Breukelen Park",
    scores: {
      cleanliness: 4,
      dog_friendliness: 4,
      busyness: 3,
      water_availability: 4,
      wastebag_availability: 4,
      trash_availability: 4,
      surface: 3,
      amenities: 3,
    },
    comment: 'It is convenience to have such a palce in our community',
    dog_size: "medium"
  },

  {
    userEmail: "owen.carver@example.com",
    parkName: "Canarsie Park",
    scores: {
      cleanliness: 5,
      dog_friendliness: 5,
      busyness: 4,
      water_availability: 5,
      wastebag_availability: 5,
      trash_availability: 5,
      surface: 4,
      amenities: 4,
    },
    comment: 'Usually not busy in evening',
    dog_size: "small"
  },

  {
    userEmail: "harrison.kim@example.com",
    parkName: "Grand Ferry Park",
    scores: {
      cleanliness: 3,
      dog_friendliness: 3,
      busyness: 2,
      water_availability: 5,
      wastebag_availability: 2,
      trash_availability: 2,
      surface: 4,
      amenities: 3,
    },
    comment: 'Always lacking of waste bag!',
    dog_size: "large"
  },

   {    
    userEmail: "colton.reese@example.com",
    parkName: "Hillside Park",
    scores: {
      cleanliness: 5,
      dog_friendliness: 5,
      busyness: 5,
      water_availability: 5,
      wastebag_availability: 5,
      trash_availability: 4,
      surface: 4,
      amenities: 4,
    },
    comment: 'Not bad',
    dog_size: "small"
  },
  {    
    userEmail: "colton.reese@example.com",
    parkName: "Dyckman Fields",
    scores: {
      cleanliness: 4,
      dog_friendliness: 5,
      busyness: 4,
      water_availability: 5,
      wastebag_availability: 5,
      trash_availability: 5,
      surface: 4,
      amenities: 4,
    },
    comment: 'My dog loves here',
    dog_size: "small"
  },
  {
    userEmail: "maya.singh@example.com",
    parkName: "Prospect Park",
    scores: {
      cleanliness: 5,
      dog_friendliness: 5,
      busyness: 4,
      water_availability: 4,
      wastebag_availability: 4,
      trash_availability: 4,
      surface: 5,
      amenities: 5,
    },
    comment: "Huge space and great vibe!",
    dog_size: "medium",
  },
  {
    userEmail: "owen.carver@example.com",
    parkName: "Prospect Park",
    scores: {
      cleanliness: 4,
      dog_friendliness: 5,
      busyness: 3,
      water_availability: 4,
      wastebag_availability: 4,
      trash_availability: 4,
      surface: 4,
      amenities: 5,
    },
    comment: "My dog can run forever here.",
    dog_size: "large",
  },

  {
    userEmail: "lucas.price@example.com",
    parkName: "Central Park",
    scores: {
      cleanliness: 4,
      dog_friendliness: 5,
      busyness: 5,
      water_availability: 4,
      wastebag_availability: 3,
      trash_availability: 4,
      surface: 4,
      amenities: 5,
    },
    comment: "Iconic and very dog friendly (busy though).",
    dog_size: "medium",
  },
  {
    userEmail: "sienna.morrison@example.com",
    parkName: "Central Park",
    scores: {
      cleanliness: 5,
      dog_friendliness: 5,
      busyness: 4,
      water_availability: 4,
      wastebag_availability: 4,
      trash_availability: 4,
      surface: 4,
      amenities: 5,
    },
    comment: "Best mornings for dogs.",
    dog_size: "small",
  },

  {
    userEmail: "ezra.kaplan@example.com",
    parkName: "Madison Square Park",
    scores: {
      cleanliness: 4,
      dog_friendliness: 4,
      busyness: 4,
      water_availability: 3,
      wastebag_availability: 3,
      trash_availability: 4,
      surface: 4,
      amenities: 4,
    },
    comment: "Nice park, a bit crowded at lunch.",
    dog_size: "small",
  },
  {
    userEmail: "harrison.kim@example.com",
    parkName: "Madison Square Park",
    scores: {
      cleanliness: 5,
      dog_friendliness: 4,
      busyness: 3,
      water_availability: 4,
      wastebag_availability: 3,
      trash_availability: 4,
      surface: 4,
      amenities: 4,
    },
    comment: "Clean and convenient.",
    dog_size: "medium",
  },

  {
    userEmail: "maya.singh@example.com",
    parkName: "Washington Square Park",
    scores: {
      cleanliness: 4,
      dog_friendliness: 5,
      busyness: 5,
      water_availability: 3,
      wastebag_availability: 3,
      trash_availability: 4,
      surface: 4,
      amenities: 4,
    },
    comment: "Super lively, dogs love it.",
    dog_size: "medium",
  },
  {
    userEmail: "owen.carver@example.com",
    parkName: "Washington Square Park",
    scores: {
      cleanliness: 4,
      dog_friendliness: 4,
      busyness: 4,
      water_availability: 3,
      wastebag_availability: 3,
      trash_availability: 4,
      surface: 4,
      amenities: 4,
    },
    comment: "Good spot, can be noisy.",
    dog_size: "large",
  },

  {
    userEmail: "lucas.price@example.com",
    parkName: "McCarren Park",
    scores: {
      cleanliness: 4,
      dog_friendliness: 4,
      busyness: 4,
      water_availability: 4,
      wastebag_availability: 4,
      trash_availability: 4,
      surface: 4,
      amenities: 4,
    },
    comment: "Solid neighborhood park.",
    dog_size: "medium",
  },
  {
    userEmail: "ezra.kaplan@example.com",
    parkName: "McCarren Park",
    scores: {
      cleanliness: 3,
      dog_friendliness: 4,
      busyness: 5,
      water_availability: 3,
      wastebag_availability: 3,
      trash_availability: 3,
      surface: 4,
      amenities: 4,
    },
    comment: "Busy but fun.",
    dog_size: "small",
  },
];