export const ratingsData = [
  {    
    cleanliness: 4,
    dog_friendliness: 5,
    busyness: 3,
    water_availability: 4,
    wastebag_availability: 5,
    trash_availability: 4,
    surface: 3,
    amenities: 4,
    dog_size: "medium"
  },
  {
    cleanliness: 5,
    dog_friendliness: 4,
    busyness: 2,
    water_availability: 5,
    wastebag_availability: 4,
    trash_availability: 4,
    surface: 4,
    amenities: 3,
    dog_size: "small"
  },
  {
    cleanliness: 3,
    dog_friendliness: 5,
    busyness: 4,
    water_availability: 3,
    wastebag_availability: 3,
    trash_availability: 3,
    surface: 4,
    amenities: 5,
    dog_size: "large"
  },
  {
    cleanliness: 4,
    dog_friendliness: 4,
    busyness: 3,
    water_availability: 4,
    wastebag_availability: 4,
    trash_availability: 4,
    surface: 3,
    amenities: 3,
    dog_size: "medium"
  },
  {
    cleanliness: 5,
    dog_friendliness: 3,
    busyness: 4,
    water_availability: 5,
    wastebag_availability: 5,
    trash_availability: 5,
    surface: 4,
    amenities: 4,
    dog_size: "small"
  },
   {    
    cleanliness: 4,
    dog_friendliness: 5,
    busyness: 3,
    water_availability: 3,
    wastebag_availability: 5,
    trash_availability: 3,
    surface: 3,
    amenities: 5,
    dog_size: "large"
  },
   {    
    cleanliness: 4,
    dog_friendliness: 3,
    busyness: 5,
    water_availability: 4,
    wastebag_availability: 5,
    trash_availability: 3,
    surface: 3,
    amenities: 4,
    dog_size: "medium"
  },
  {    
    cleanliness: 3,
    dog_friendliness: 3,
    busyness: 2,
    water_availability: 2,
    wastebag_availability: 3,
    trash_availability: 3,
    surface: 3,
    amenities: 4,
    dog_size: "small"
  },
  {    
    cleanliness: 2,
    dog_friendliness: 5,
    busyness: 3,
    water_availability: 5,
    wastebag_availability: 3,
    trash_availability: 3,
    surface: 3,
    amenities: 3,
    dog_size: "large"
  },
  {    
    cleanliness: 4,
    dog_friendliness: 5,
    busyness: 5,
    water_availability: 4,
    wastebag_availability: 5,
    trash_availability: 3,
    surface: 3,
    amenities: 5,
    dog_size: "medium"
  },
  {    
    cleanliness: 4,
    dog_friendliness: 1,
    busyness: 5,
    water_availability: 3,
    wastebag_availability: 5,
    trash_availability: 3,
    surface: 4,
    amenities: 4,
    dog_size: "small"
  },
  {
    cleanliness: 5,
    dog_friendliness: 4,
    busyness: 2,
    water_availability: 3,
    wastebag_availability: 3,
    trash_availability: 4,
    surface: 3,
    amenities: 3,
    dog_size: "small"
  },
  {
    cleanliness: 4,
    dog_friendliness: 4,
    busyness: 2,
    water_availability: 5,
    wastebag_availability: 4,
    trash_availability: 5,
    surface: 4,
    amenities: 4,
    dog_size: "medium"
  },
  {
    cleanliness: 3,
    dog_friendliness: 4,
    busyness: 4,
    water_availability: 5,
    wastebag_availability: 4,
    trash_availability: 3,
    surface: 4,
    amenities: 3,
    dog_size: "small"
  },
];