export const usersData = [
  {
    "dog_name": "Molly Moo",
    "human_first_name": "Lucas",
    "human_last_name": "Price",
    "dog_gender": "F",
    "human_gender": "M",
    "email": "lucas.price@example.com",
    "hashed_password": "h82ksla9",
    "role": "user",
    "favorite_parks": [],
    "times": ["08:00-09:00", "14:00-15:00"],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },
  {
    "dog_name": "Rocket",
    "human_first_name": "Sienna",
    "human_last_name": "Morrison",
    "dog_gender": "M",
    "human_gender": "F",
    "email": "sienna.morrison@example.com",
    "hashed_password": "p3ka77tw",
    "role": "user",
    "favorite_parks": [],
    "times": ["09:00-10:00"],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },
  {
    "dog_name": "Pumpkin",
    "human_first_name": "Ezra",
    "human_last_name": "Kaplan",
    "dog_gender": "F",
    "human_gender": "M",
    "email": "ezra.kaplan@example.com",
    "hashed_password": "kx22wm3n",
    "role": "user",
    "favorite_parks": [],
    "times": ["11:00-12:00", "17:00-18:00", "19:00-20:00"],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },
  {
    "dog_name": "Taco",
    "human_first_name": "Maya",
    "human_last_name": "Singh",
    "dog_gender": "M",
    "human_gender": "F",
    "email": "maya.singh@example.com",
    "hashed_password": "b83mvx21",
    "role": "user",
    "favorite_parks": [],
    "times": ["07:00-08:00"],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },
  {
    "dog_name": "Shadow",
    "human_first_name": "Owen",
    "human_last_name": "Carver",
    "dog_gender": "M",
    "human_gender": "M",
    "email": "owen.carver@example.com",
    "hashed_password": "pff22lks",
    "role": "user",
    "favorite_parks": [],
    "times": ["08:00-09:00", "15:00-16:00", "18:00-19:00"],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },
  {
    "dog_name": "Cinnamon",
    "human_first_name": "Aaliyah",
    "human_last_name": "Brooks",
    "dog_gender": "F",
    "human_gender": "F",
    "email": "aaliyah.brooks@example.com",
    "hashed_password": "mm29shq2",
    "role": "user",
    "favorite_parks": [],
    "times": ["10:00-11:00", "13:00-14:00", "20:00-21:00", "21:00-22:00"],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },
  {
    "dog_name": "Boomer",
    "human_first_name": "Wyatt",
    "human_last_name": "Ramirez",
    "dog_gender": "M",
    "human_gender": "M",
    "email": "wyatt.ramirez@example.com",
    "hashed_password": "t1x02akp",
    "role": "user",
    "favorite_parks": [],
    "times": ["06:00-07:00", "16:00-17:00"],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },
  {
    "dog_name": "Noodle",
    "human_first_name": "Isabelle",
    "human_last_name": "Garcia",
    "dog_gender": "F",
    "human_gender": "F",
    "email": "isabelle.g@example.com",
    "hashed_password": "lc88w1nz",
    "role": "user",
    "favorite_parks": [],
    "times": ["09:00-10:00", "18:00-19:00"],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },
  {
    "dog_name": "Zeus",
    "human_first_name": "Harrison",
    "human_last_name": "Kim",
    "dog_gender": "M",
    "human_gender": "M",
    "email": "harrison.kim@example.com",
    "hashed_password": "w9sk4p22",
    "role": "user",
    "favorite_parks": [],
    "times": ["12:00-13:00", "13:00-14:00", "19:00-20:00"],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },
  {
    "dog_name": "Princess Pickles",
    "human_first_name": "Lila",
    "human_last_name": "Wang",
    "dog_gender": "F",
    "human_gender": "F",
    "email": "lila.wang@example.com",
    "hashed_password": "smm229da",
    "role": "user",
    "favorite_parks": [],
    "times": ["15:00-16:00"],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },

  {
    "dog_name": "Barkley",
    "human_first_name": "Evan",
    "human_last_name": "Kennedy",
    "dog_gender": "M",
    "human_gender": "M",
    "email": "evan.kennedy@example.com",
    "hashed_password": "ka7712lp",
    "role": "user",
    "favorite_parks": [],
    "times": ["10:00-11:00", "16:00-17:00", "17:00-18:00"],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },
  {
    "dog_name": "Jellybean",
    "human_first_name": "Ruby",
    "human_last_name": "Adler",
    "dog_gender": "F",
    "human_gender": "F",
    "email": "ruby.adler@example.com",
    "hashed_password": "a29mzq11",
    "role": "user",
    "favorite_parks": [],
    "times": ["08:00-09:00"],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },
  {
    "dog_name": "Fudge",
    "human_first_name": "Miles",
    "human_last_name": "Dawson",
    "dog_gender": "M",
    "human_gender": "M",
    "email": "miles.dawson@example.com",
    "hashed_password": "pwq772lm",
    "role": "user",
    "favorite_parks": [],
    "times": ["07:00-08:00", "18:00-19:00", "21:00-22:00"],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },
  {
    "dog_name": "Poppy",
    "human_first_name": "Nora",
    "human_last_name": "Fleming",
    "dog_gender": "F",
    "human_gender": "F",
    "email": "nora.fleming@example.com",
    "hashed_password": "u73bbx29",
    "role": "user",
    "favorite_parks": [],
    "times": ["13:00-14:00", "14:00-15:00"],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },

  {
    "dog_name": "Teddy",
    "human_first_name": "Colton",
    "human_last_name": "Reese",
    "dog_gender": "M",
    "human_gender": "M",
    "email": "colton.reese@example.com",
    "hashed_password": "mm3x92aa",
    "role": "user",
    "favorite_parks": [],
    "times": ["09:00-10:00", "11:00-12:00", "20:00-21:00"],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },
  {
    "dog_name": "Ladybug",
    "human_first_name": "Emily",
    "human_last_name": "Shaw",
    "dog_gender": "F",
    "human_gender": "F",
    "email": "emily.shaw@example.com",
    "hashed_password": "k2ls8q12",
    "role": "user",
    "favorite_parks": [],
    "times": ["06:00-07:00", "15:00-16:00", "22:00-23:00"],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },

  {
    "dog_name": "Churro",
    "human_first_name": "Aiden",
    "human_last_name": "Bishop",
    "dog_gender": "M",
    "human_gender": "M",
    "email": "aiden.bishop@example.com",
    "hashed_password": "b1sz99pp",
    "role": "user",
    "favorite_parks": [],
    "times": ["12:00-13:00"],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },
  {
    "dog_name": "Peppermint",
    "human_first_name": "Naomi",
    "human_last_name": "Chen",
    "dog_gender": "F",
    "human_gender": "F",
    "email": "naomi.chen@example.com",
    "hashed_password": "aa32nz09",
    "role": "user",
    "favorite_parks": [],
    "times": ["08:00-09:00", "17:00-18:00"],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },

  {
    "dog_name": "Bruno",
    "human_first_name": "Caleb",
    "human_last_name": "Dixon",
    "dog_gender": "M",
    "human_gender": "M",
    "email": "caleb.dixon@example.com",
    "hashed_password": "dks882aa",
    "role": "user",
    "favorite_parks": [],
    "times": ["10:00-11:00", "19:00-20:00", "20:00-21:00"],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },

  {
    "dog_name": "Test",
    "human_first_name": "Test",
    "human_last_name": "Test",
    "dog_gender": "M",
    "human_gender": "M",
    "email": "test@gmail.com",
    "hashed_password": "$2b$10$BTjQGPak6uIOTm/qZuHN/OmHIg4phzanGjemfsOZlP.vETuv3sffy",
    "role": "admin",
    "favorite_parks": [],
    "times": ["10:00-11:00", "19:00-20:00", "20:00-21:00"],
    "ratings": [],
    "pet_friends": ["6928828668069db7f55b709d"],
    "biscuits": ["692cba3179658ab9a869f358"],
    "parks_visited": []
  }
];