export const usersData = [
  {
    "dog_name": "Molly Moo",
    "human_first_name": "Lucas",
    "human_last_name": "Price",
    "dog_gender": "female",
    "human_gender": "male",
    "email": "lucas.price@example.com",
    "password": "Gp9!sLqa",
    "role": "user",
    "favorite_parks": [],
    "times": [],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },
  {
    "dog_name": "Rocket",
    "human_first_name": "Sienna",
    "human_last_name": "Morrison",
    "dog_gender": "male",
    "human_gender": "female",
    "email": "sienna.morrison@example.com",
    "password": "Qe4@Lm82",
    "role": "user",
    "favorite_parks": [],
    "times": [],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },
  {
    "dog_name": "Pumpkin",
    "human_first_name": "Ezra",
    "human_last_name": "Kaplan",
    "dog_gender": "female",
    "human_gender": "male",
    "email": "ezra.kaplan@example.com",
    "password": "Tr1#pwX9",
    "role": "user",
    "favorite_parks": [],
    "times": [],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },
  {
    "dog_name": "Taco",
    "human_first_name": "Maya",
    "human_last_name": "Singh",
    "dog_gender": "male",
    "human_gender": "female",
    "email": "maya.singh@example.com",
    "password": "Wk7!Psam",
    "role": "user",
    "favorite_parks": [],
    "times": [],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },
  {
    "dog_name": "Shadow",
    "human_first_name": "Owen",
    "human_last_name": "Carver",
    "dog_gender": "male",
    "human_gender": "male",
    "email": "owen.carver@example.com",
    "password": "Rb2@Nkq5",
    "role": "user",
    "favorite_parks": [],
    "times": [],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },
  {
    "dog_name": "Cinnamon",
    "human_first_name": "Aaliyah",
    "human_last_name": "Brooks",
    "dog_gender": "female",
    "human_gender": "female",
    "email": "aaliyah.brooks@example.com",
    "password": "Ks8$Tyla",
    "role": "user",
    "favorite_parks": [],
    "times": [],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },
  {
    "dog_name": "Boomer",
    "human_first_name": "Wyatt",
    "human_last_name": "Ramirez",
    "dog_gender": "male",
    "human_gender": "male",
    "email": "wyatt.ramirez@example.com",
    "password": "Yt3!Lop2",
    "role": "user",
    "favorite_parks": [],
    "times": [],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },
  {
    "dog_name": "Noodle",
    "human_first_name": "Isabelle",
    "human_last_name": "Garcia",
    "dog_gender": "female",
    "human_gender": "female",
    "email": "isabelle.g@example.com",
    "password": "Mf9@Sld3",
    "role": "user",
    "favorite_parks": [],
    "times": [],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },
  {
    "dog_name": "Zeus",
    "human_first_name": "Harrison",
    "human_last_name": "Kim",
    "dog_gender": "male",
    "human_gender": "male",
    "email": "harrison.kim@example.com",
    "password": "Lp4$Rmz8",
    "role": "user",
    "favorite_parks": [],
    "times": [],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },
  {
    "dog_name": "Princess Pickles",
    "human_first_name": "Lila",
    "human_last_name": "Wang",
    "dog_gender": "female",
    "human_gender": "female",
    "email": "lila.wang@example.com",
    "password": "Hg2!Pmel",
    "role": "user",
    "favorite_parks": [],
    "times": [],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },

  {
    "dog_name": "Barkley",
    "human_first_name": "Evan",
    "human_last_name": "Kennedy",
    "dog_gender": "male",
    "human_gender": "male",
    "email": "evan.kennedy@example.com",
    "password": "Zv6@Bmqo",
    "role": "user",
    "favorite_parks": [],
    "times": [],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },

  {
    "dog_name": "Jellybean",
    "human_first_name": "Ruby",
    "human_last_name": "Adler",
    "dog_gender": "female",
    "human_gender": "female",
    "email": "ruby.adler@example.com",
    "password": "Dx7!Qnva",
    "role": "user",
    "favorite_parks": [],
    "times": [],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },

  {
    "dog_name": "Fudge",
    "human_first_name": "Miles",
    "human_last_name": "Dawson",
    "dog_gender": "male",
    "human_gender": "male",
    "email": "miles.dawson@example.com",
    "password": "Wf9#Lpt1",
    "role": "user",
    "favorite_parks": [],
    "times": [],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },

  {
    "dog_name": "Poppy",
    "human_first_name": "Nora",
    "human_last_name": "Fleming",
    "dog_gender": "female",
    "human_gender": "female",
    "email": "nora.fleming@example.com",
    "password": "Ae5$Tmq4",
    "role": "user",
    "favorite_parks": [],
    "times": [],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },

  {
    "dog_name": "Teddy",
    "human_first_name": "Colton",
    "human_last_name": "Reese",
    "dog_gender": "male",
    "human_gender": "male",
    "email": "colton.reese@example.com",
    "password": "Nm4!Sqo9",
    "role": "user",
    "favorite_parks": [],
    "times": [],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },

  {
    "dog_name": "Ladybug",
    "human_first_name": "Emily",
    "human_last_name": "Shaw",
    "dog_gender": "female",
    "human_gender": "female",
    "email": "emily.shaw@example.com",
    "password": "Xy3@Pmz2",
    "role": "user",
    "favorite_parks": [],
    "times": [],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },

  {
    "dog_name": "Churro",
    "human_first_name": "Aiden",
    "human_last_name": "Bishop",
    "dog_gender": "male",
    "human_gender": "male",
    "email": "aiden.bishop@example.com",
    "password": "Vr8!Lpka",
    "role": "user",
    "favorite_parks": [],
    "times": [],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },

  {
    "dog_name": "Peppermint",
    "human_first_name": "Naomi",
    "human_last_name": "Chen",
    "dog_gender": "female",
    "human_gender": "female",
    "email": "naomi.chen@example.com",
    "password": "Qt2$Wlne",
    "role": "user",
    "favorite_parks": [],
    "times": [],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },

  {
    "dog_name": "Bruno",
    "human_first_name": "Caleb",
    "human_last_name": "Dixon",
    "dog_gender": "male",
    "human_gender": "male",
    "email": "caleb.dixon@example.com",
    "password": "Rp6!Qtle",
    "role": "user",
    "favorite_parks": [],
    "times": [],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  },

  {
    "dog_name": "Test",
    "human_first_name": "Test",
    "human_last_name": "Test",
    "dog_gender": "male",
    "human_gender": "male",
    "email": "test@gmail.com",
    "password": "Testing123!",
    "role": "admin",
    "favorite_parks": [],
    "times": [],
    "ratings": [],
    "pet_friends": [],
    "biscuits": [],
    "parks_visited": []
  }
];
