export const usersData = [
  {
    dogName: "Molly Moo",
    humanFirstName: "Lucas",
    humanLastName: "Price",
    dogGender: "female",
    humanGender: "male",
    email: "lucas.price@example.com",
    password: "Gp9!sLqa",
    bio: "Molly Moo loves long walks and chasing tennis balls!",
    role: "user",
    favoriteParks: [],
    times: [],
    ratings: [],
    petFriends: [],
    biscuits: [],
    parksVisited: []
  },
  {
    dogName: "Rocket",
    humanFirstName: "Sienna",
    humanLastName: "Morrison",
    dogGender: "male",
    humanGender: "female",
    email: "sienna.morrison@example.com",
    password: "Qe4@Lm82",
    bio: "Rocket is a playful pup who loves meeting new friends.",
    role: "user",
    favoriteParks: [],
    times: [],
    ratings: [],
    petFriends: [],
    biscuits: [],
    parksVisited: []
  },
  {
    dogName: "Pumpkin",
    humanFirstName: "Ezra",
    humanLastName: "Kaplan",
    dogGender: "female",
    humanGender: "male",
    email: "ezra.kaplan@example.com",
    password: "Tr1#pwX9",
    bio: "Pumpkin enjoys belly rubs and naps in the sun.",
    role: "user",
    favoriteParks: [],
    times: [],
    ratings: [],
    petFriends: [],
    biscuits: [],
    parksVisited: []
  },
  {
    dogName: "Taco",
    humanFirstName: "Maya",
    humanLastName: "Singh",
    dogGender: "male",
    humanGender: "female",
    email: "maya.singh@example.com",
    password: "Wk7!Psam",
    bio: "Taco loves adventures, especially in new parks!",
    role: "user",
    favoriteParks: [],
    times: [],
    ratings: [],
    petFriends: [],
    biscuits: [],
    parksVisited: []
  },
  {
    dogName: "Shadow",
    humanFirstName: "Owen",
    humanLastName: "Carver",
    dogGender: "male",
    humanGender: "male",
    email: "owen.carver@example.com",
    password: "Rb2@Nkq5",
    bio: "Shadow is shy at first but very loyal once friends.",
    role: "user",
    favoriteParks: [],
    times: [],
    ratings: [],
    petFriends: [],
    biscuits: [],
    parksVisited: []
  },
  {
    dogName: "Cinnamon",
    humanFirstName: "Aaliyah",
    humanLastName: "Brooks",
    dogGender: "female",
    humanGender: "female",
    email: "aaliyah.brooks@example.com",
    password: "Ks8$Tyla",
    bio: "Cinnamon enjoys cuddles and sniffing around the park.",
    role: "user",
    favoriteParks: [],
    times: [],
    ratings: [],
    petFriends: [],
    biscuits: [],
    parksVisited: []
  },
  {
    dogName: "Boomer",
    humanFirstName: "Wyatt",
    humanLastName: "Ramirez",
    dogGender: "male",
    humanGender: "male",
    email: "wyatt.ramirez@example.com",
    password: "Yt3!Lop2",
    bio: "Boomer loves running fast and playing fetch.",
    role: "user",
    favoriteParks: [],
    times: [],
    ratings: [],
    petFriends: [],
    biscuits: [],
    parksVisited: []
  },
  {
    dogName: "Noodle",
    humanFirstName: "Isabelle",
    humanLastName: "Garcia",
    dogGender: "female",
    humanGender: "female",
    email: "isabelle.g@example.com",
    password: "Mf9@Sld3",
    bio: "Noodle is gentle and loves snacking on treats.",
    role: "user",
    favoriteParks: [],
    times: [],
    ratings: [],
    petFriends: [],
    biscuits: [],
    parksVisited: []
  },
  {
    dogName: "Zeus",
    humanFirstName: "Harrison",
    humanLastName: "Kim",
    dogGender: "male",
    humanGender: "male",
    email: "harrison.kim@example.com",
    password: "Lp4$Rmz8",
    bio: "Zeus is brave and loves guarding his human.",
    role: "user",
    favoriteParks: [],
    times: [],
    ratings: [],
    petFriends: [],
    biscuits: [],
    parksVisited: []
  },
  {
    dogName: "Princess Pickles",
    humanFirstName: "Lila",
    humanLastName: "Wang",
    dogGender: "female",
    humanGender: "female",
    email: "lila.wang@example.com",
    password: "Hg2!Pmel",
    bio: "Princess Pickles loves pampering and royal naps.",
    role: "user",
    favoriteParks: [],
    times: [],
    ratings: [],
    petFriends: [],
    biscuits: [],
    parksVisited: []
  },
  {
    dogName: "Barkley",
    humanFirstName: "Evan",
    humanLastName: "Kennedy",
    dogGender: "male",
    humanGender: "male",
    email: "evan.kennedy@example.com",
    password: "Zv6@Bmqo",
    bio: "Barkley is cheerful and loves meeting new friends.",
    role: "user",
    favoriteParks: [],
    times: [],
    ratings: [],
    petFriends: [],
    biscuits: [],
    parksVisited: []
  },
  {
    dogName: "Jellybean",
    humanFirstName: "Ruby",
    humanLastName: "Adler",
    dogGender: "female",
    humanGender: "female",
    email: "ruby.adler@example.com",
    password: "Dx7!Qnva",
    bio: "Jellybean is sweet and loves playing with toys.",
    role: "user",
    favoriteParks: [],
    times: [],
    ratings: [],
    petFriends: [],
    biscuits: [],
    parksVisited: []
  },
  {
    dogName: "Fudge",
    humanFirstName: "Miles",
    humanLastName: "Dawson",
    dogGender: "male",
    humanGender: "male",
    email: "miles.dawson@example.com",
    password: "Wf9#Lpt1",
    bio: "Fudge is playful and loves rolling in the grass.",
    role: "user",
    favoriteParks: [],
    times: [],
    ratings: [],
    petFriends: [],
    biscuits: [],
    parksVisited: []
  },
  {
    dogName: "Poppy",
    humanFirstName: "Nora",
    humanLastName: "Fleming",
    dogGender: "female",
    humanGender: "female",
    email: "nora.fleming@example.com",
    password: "Ae5$Tmq4",
    bio: "Poppy loves sniffing flowers and making friends.",
    role: "user",
    favoriteParks: [],
    times: [],
    ratings: [],
    petFriends: [],
    biscuits: [],
    parksVisited: []
  },
  {
    dogName: "Teddy",
    humanFirstName: "Colton",
    humanLastName: "Reese",
    dogGender: "male",
    humanGender: "male",
    email: "colton.reese@example.com",
    password: "Nm4!Sqo9",
    bio: "Teddy loves running and exploring new places.",
    role: "user",
    favoriteParks: [],
    times: [],
    ratings: [],
    petFriends: [],
    biscuits: [],
    parksVisited: []
  },
  {
    dogName: "Ladybug",
    humanFirstName: "Emily",
    humanLastName: "Shaw",
    dogGender: "female",
    humanGender: "female",
    email: "emily.shaw@example.com",
    password: "Xy3@Pmz2",
    bio: "Ladybug is sweet and loves chasing butterflies.",
    role: "user",
    favoriteParks: [],
    times: [],
    ratings: [],
    petFriends: [],
    biscuits: [],
    parksVisited: []
  },
  {
    dogName: "Churro",
    humanFirstName: "Aiden",
    humanLastName: "Bishop",
    dogGender: "male",
    humanGender: "male",
    email: "aiden.bishop@example.com",
    password: "Vr8!Lpka",
    bio: "Churro is curious and loves to dig around.",
    role: "user",
    favoriteParks: [],
    times: [],
    ratings: [],
    petFriends: [],
    biscuits: [],
    parksVisited: []
  },
  {
    dogName: "Peppermint",
    humanFirstName: "Naomi",
    humanLastName: "Chen",
    dogGender: "female",
    humanGender: "female",
    email: "naomi.chen@example.com",
    password: "Qt2$Wlne",
    bio: "Peppermint enjoys cuddles and long walks.",
    role: "user",
    favoriteParks: [],
    times: [],
    ratings: [],
    petFriends: [],
    biscuits: [],
    parksVisited: []
  },
  {
    dogName: "Bruno",
    humanFirstName: "Caleb",
    humanLastName: "Dixon",
    dogGender: "male",
    humanGender: "male",
    email: "caleb.dixon@example.com",
    password: "Rp6!Qtle",
    bio: "Bruno loves running, playing fetch, and napping.",
    role: "user",
    favoriteParks: [],
    times: [],
    ratings: [],
    petFriends: [],
    biscuits: [],
    parksVisited: []
  },
  {
    dogName: "Test",
    humanFirstName: "Test",
    humanLastName: "Test",
    dogGender: "male",
    humanGender: "male",
    email: "test@gmail.com",
    password: "Testing123!",
    bio: "Test dog account for admin purposes.",
    role: "admin",
    favoriteParks: [],
    times: [],
    ratings: [],
    petFriends: [],
    biscuits: [],
    parksVisited: []
  }
];
